import type { Metadata } from "next";
import "../globals.css";
import Providers from "../Providers";
import { ReactNode } from "react";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import Continer from "@/components/global/Continer";
import Navhero from "@/components/navbar/Navhero";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Navhero session={session} />
          <Continer>{children}</Continer>
        </Providers>
      </body>
    </html>
  );
}
