import type { Metadata } from "next";
import "../globals.css";
import Providers from "../Providers";
import { ReactNode } from "react";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import Navhero from "@/components/navbar/Navhero";
import Footer from "@/components/home/Footer";
import Script from "next/script";
import "@fancyapps/ui/dist/fancybox/fancybox.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_GOOGLE_API_KEY_MAP}`}
          strategy="beforeInteractive"
          async
          defer
        />
      </head>
      <body>
        <Providers>
          <Navhero session={session} />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
